name: Latest blog post workflow
on:
  schedule: # Run workflow automatically
    - cron: '0 8 * * *' # Cron job every day 8am
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the Github Actions Workflow page directly

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pull in blogs.cisco.com/developer posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "http://blogs.cisco.com/developer/feed"
          readme_path: ./profile/README.md
